# Re-Shaping Arrays

In [1]:
import numpy as np 

arr = np.arange(8)
print(arr)
print()
print(arr.reshape(4,2))

    

[0 1 2 3 4 5 6 7]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


"C" order "Row" Major and "Fortran" Order "Column" Major   AND if both row and column are major order than called as C and Fortan Order.

The -1 parameter in the reshape method indicates that numpy should automatically calculate the number of columns based on the size of the original 
array and the desired number of rows, which in this case is 5. Since the original array has 15 elements, numpy calculates that the resulting two-dimensional array should have 5 rows and 3 columns.


In [14]:
arr = np.arange(15)
print(arr.reshape(5,-1))
print()
arr.ravel() # multi dimension array lai ravel/flatten function ley one dimension banaucha

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

The opposite operation of reshape from one dimension to heigher dimension is typically know as flatten or ravel

In [12]:
arr = np.arange(15)
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])