# Broadcasting in Numpy:

In [4]:
import numpy as np

var1 = np.array([1,2,3,4])

var2 = np.array([1,2,2]) # element are not equall so this error occur in broadcasting

print(var1  + var2)  # ValueError: operands could not be broadcast together with shapes (4,) (3,) this error comes because number of elements are not same in one dimension array 


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [5]:
var_x = np.array([1,2,3,4])  # Dimension should be same or values of the element should be same to perform broadcasting

var_y = np.array([1,2,2,5]) 

print(var_x  + var_y)

[2 4 5 9]


In [11]:
x = np.array([1,2,3])
print(x.shape)
print()
print(x)

(3,)

[1 2 3]


In [17]:
A = np.array([[1],[2],[3]])
print(A.shape)
print(A)

(3, 1)
[[1]
 [2]
 [3]]


In [7]:
B = np.array([1],[2])
print(B.shape)

C = np.array([1,2,3],[1,2,3])
print(C.shape)

print(B+C)

TypeError: Field elements must be 2- or 3-tuples, got '2'