# Shape

In [3]:
import numpy as np

var = np.array([[1,2,4],[1,2,3]])
print(var)
print()
print("The shape of the array are :",var.shape)

[[1 2 4]
 [1 2 3]]

The shape/row and column of the array are : (2, 3)


In [7]:
var1 = np.array([1,2,4,6], ndmin = 4) # ndmin function use to create multi-dimensional array here ndmin = 4 means 4 dimension array is create
print(var1)

print(f"It is {var1.ndim} dimension array")
print() # for new space/line
print("The shape of the array are :", var1.shape) # number of row are 111 and  column are 4

[[[[1 2 4 6]]]]
It is 4 dimension array

The shape of the array are : (1, 1, 1, 4)


# Re-shape 

In [19]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(f"It is {var2.ndim} dimension array")
print()
varx = var2.reshape(3,2) # reshape(no.of rows, no.column)
print(varx)
print(f"It is {varx.ndim} dimension array")

[1 2 3 4 5 6]
It is 1 dimension array

[[1 2]
 [3 4]
 [5 6]]
It is 2 dimension array


In [18]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(f"It is {var3.ndim} dimension array")
print()
varz = var3.reshape(2,3,2) # reshape(no.of rows, no.column)
print(varz)
print(f"It is {varz.ndim} dimension array")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
It is 1 dimension array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
It is 3 dimension array


# Converting 3D/2D Array to 1D array


In [21]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(f"It is {var3.ndim} dimension array")
print()
varz = var3.reshape(2,3,2) # reshape(no.of rows, no.column)
print(varz)
print(f"It is {varz.ndim} dimension array")

print()

one = varz.reshape(-1)
print(one)
print(f"It is {one.ndim}D array")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
It is 1 dimension array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
It is 3 dimension array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
It is 1D array
