In [1]:
import numpy as np

# rand()
This function is used to generate random value between 0 to 1

In [2]:
x = np.random.rand(4) # 4 array will be created with value between 0 and 1
print(x)

[0.67131214 0.70170435 0.87257768 0.3805066 ]


In [5]:
y = np.random.rand(3,4) # Multi dimension array
print(y)

[[0.18931481 0.47441565 0.84878792 0.56291638]
 [0.55972431 0.85051468 0.18297326 0.84393053]
 [0.51030209 0.75937575 0.35479408 0.23276449]]


# randn() 
This function is used to generate a random value close to zero. This may return positive or negative number as well

In [6]:
var = np.random.randn(5) # randomly created 5 number close to zero and both -ve and +ve
print(var)

[ 0.30784235 -0.25834455  1.04258989  0.24045118  0.9562598 ]


# ranf()
The given function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval[0.0, 1)

#But here including 0 but excluding 1 will be generated.

In [7]:
varx = np.random.ranf(6)
print(varx)

[0.3346791  0.57982793 0.95380585 0.30706945 0.23105866 0.51538902]


# randint() 
used to generate a random number between a given range

In [13]:
#random.randint(min,max,total_value)
vary = np.random.randint(6,18,4) # each time new number is generated it will print upto 18 only
print(vary)

[14 10  7 11]
