# Array

In [7]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)  #changing list into array
print(y)         #Directly Shows array
y                #It print Value of y with data type
type(y)          # data type 

[1 2 3 4 5]


numpy.ndarray

In [10]:
l = []
for i in range(1,5): #Here only 4 array will be taken as input 
    x = int(input("Enter value :"))
    l.append(x)
print(np.array(l))

Enter value :2
Enter value :2
Enter value :2
Enter value :2
[2 2 2 2]


# Two Dimension(2D) Array

In [13]:
ar2 =np.array ([[1,2,3,4],[1,2,3,4]])
print(ar2)
print("The dimension of the array is :",ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
The dimension of the array is : 2



# Three Dimension(3D) Array

In [14]:
ar3 = np.array([[[1,2,3],[1,2,3]]])
print(ar3)
print("The dimension of the array is :",ar3.ndim)

[[[1 2 3]
  [1 2 3]]]
The dimension of the array is : 3


# Nth Dimension Array

In [18]:
arn =np.array([1,2,3,4,5],ndmin = 10)
print(arn)
print("The dimension of the array is :",arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
The dimension of the array is : 10
