# Array Filled With Zeros

In [1]:
import numpy as np

In [7]:
arry_zero = np.zeros(6) # zeros function is used to create array but it will create one dimensional array
print(arry_zero)

[0. 0. 0. 0. 0. 0.]


In [11]:
arry_zero1 = np.zeros((4,3)) # creating 2D array and giving rows and column.
print(arry_zero1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Array Filled With One

In [13]:
arry_one = np.ones(4)# ones function is used and parameter is pass to create number od aarays
print(arry_one)

[1. 1. 1. 1.]


In [14]:
arry_one1 = np.ones((3,3))
print(arry_one1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Creating Empty Array

In [28]:
arry_empty = np.empty(1)
print(arry_empty)  # This is a empty functionhere data comes from the previously used memory.

[8.79503872e-313]


# An Array With Range of elements

In [29]:
arry_range = np.arange(6)#arange function  works similar to range function and give data 
print(arry_range)

[0 1 2 3 4 5]


# Array diagonal element filled with 1

In [31]:
arry_diagonal = np.eye(4)#eye function is  and when parameter is pass with 4 it create 4x4 element with all its diagonal 1
print(arry_diagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
arry_diagonal1 = np.eye(3,3)
print(arry_diagonal1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create an array with values that are spaced linearly in a special interval

In [19]:
ar_line = np.linspace(0,20, num=5) # linspace function is used where num = 5 means 5 element should print with evenly number space or gap
print(ar_line)

[ 0.  5. 10. 15. 20.]
