# Arthimetic function 
#a+b = np.add(a,b)
#a-b = np.substract(a,b)
#a*b = np.multiply(a,b)
#a/b = np.divide(a,b)
#a%b = np.mod(a,b)
#a**b = np.power(a,b)
#1/a = np.reciprocal


# Arthimetic Operation

In [2]:
import numpy as np

var = np.array([1,2,3,4])
add_ = var +3 
print(add_)

[4 5 6 7]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 +var2 
print(var_add)

[2 4 6 8]


In [4]:
var1 = np.array([1,2,3,4]) # using function
var2 = np.array([1,2,3,4])
var_add = np.add(var1,var2)
print(var_add)

[2 4 6 8]


In [5]:
var = np.array([1,2,3,4,5])
sub_ = var - 3 
print(sub_)

[-2 -1  0  1  2]


In [6]:
var = np.array([1,2,3,4,5])
div_ = var / 3 
print(div_)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [7]:
var = np.array([1,2,3,4,5])
mod_ = var % 3 
print(mod_)

[1 2 0 1 2]
