# Indexing

In [1]:
import numpy as np

In [3]:
var = np.array([1,2,3])
print(var[0])
print(var[-1])# we can do -ve indexing also same as in list

1
3


In [4]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[1,2])

[[1 2 3]
 [4 5 6]]
2

6


In [5]:
var2 = np.array([[[3,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[3 2]
  [6 7]]]
3

7


# Slicing

In [26]:
x = np.array([1,2,3,4,5,6])
print(x.ndim)# dimension of the array
print(x)# main array

1
[1 2 3 4 5 6]


In [27]:
print(x[1:4]) #last index will be n-1

[2 3 4]


In [29]:
print(x[0:5:1])#start 0 stop  5 step 1

[1 2 3 4 5]


In [30]:
print(x[:]) #all the value will be show

[1 2 3 4 5 6]


In [31]:
print(x[:5])#from 0 index to 4th index as it is n-1

[1 2 3 4 5]


In [32]:
print(x[2:])#from 2nd index it will run upto last

[3 4 5 6]
