# Iterating in Numpy

In [2]:
import numpy as np

In [7]:
x = np.array([1,2,3,4])
for i in x:
    print(i) #in this was it will print in vertical column

1
2
3
4


In [6]:
x = np.array([1,2,3,4])
for i in x:
    print(i , end=" ") # it will print in horizontal column

1 2 3 4 

In [16]:
Y = np.array([[1,2,3],[4,5,6]])
Y.ndim # Dimension
print()
for i in Y:
    print(i)

for j in Y:
    for m in j:
        print(m, end=" ")


[1 2 3]
[4 5 6]
1 2 3 4 5 6 

In [3]:
XY = np.array([[[1,9,5,4],[3,8,7,3]]])#3D array
XY

array([[[1, 9, 5, 4],
        [3, 8, 7, 3]]])

In [4]:
for i in np.nditer(XY):#nditer() is the function to iterate
    print(i)

1
9
5
4
3
8
7
3
