# Join Array

In [5]:
import numpy as np

In [5]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

add_arry = np.concatenate((var,var1)) # this functions merge two arrays in one
add_arry

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
var0 = np.array([[1,2],[4,5]])
var2 = np.array([[6,2],[8,5]])
arry_add = np.concatenate((var0,var2), axis = 1)
print(arry_add)

[[1 2 6 2]
 [4 5 8 5]]


Stack Function
it work along the axis only

In [8]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

new_arry = np.stack((var_1,var_2), axis = 1) 
print(new_arry)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [10]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

new_arry = np.vstack((var_1,var_2))  # vertical
print(new_arry)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

new_arry = np.vstack((var_1,var_2)) #merge along the vertical/column
print(new_arry)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([5,6,7,8])

new_arry = np.hstack((var_1,var_2)) # merge along horizontal/row
print(new_arry)

[1 2 3 4 5 6 7 8]


split array

In [15]:
X = np.array([1,2,3,4,5,6,7,8])
a1 = np.array_split(X,3) # X is splited into 3 parts
a1

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [16]:
X = np.array([1,2,3,4,5,6,7,8])
a1 = np.array_split(X,4) # X is splited into 3 parts
a1

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]